### ISSUE TITLE
Can carrier sensing be disabled?

### ISSUE THREAD

**Issue by zhitaoh** [TuGraz-ITI/JamLab-NG#3]
Can carrier sensing be disabled, so that packet injection is not throttled by presence of another jammer? I have observed that, when two jammers are partially overlapped in their signal spectrum, (e.g. one sending on channel 1 and another on channel 4), they reduced the amount of frame transmission, apparently trying to back off until the channel is clear.

**Comment by schuschu** [comment]
using nexutil you can disable it. nexutil -s0x703 -i -v 1 should do the trick. you can check if it works in the debug console using the following as root
`cat /sys/kernel/debug/brcmfmac/mmc1\:0001\:1/forensics && echo`
(the echo is used as otherwise the last line would not be shown correctly)
More on how to do it incode can be seen here (https://github.com/TuGraz-ITI/JamLab-NG/blob/master/src/ioctl.c#L396) so you could do the same as with the channel and pack it in any field of the radiotap header (https://github.com/TuGraz-ITI/JamLab-NG/blob/master/src/injection.c#L75).

**Comment by zhitaoh** [comment]
Awesome. I will try as you suggest as soon as I can. Thanks!
